export const cards = [
  {
    id: 1,
    type: "bar",
    title: "snickers",
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Snickers-broken.png/240px-Snickers-broken.png",
    alt: "snickers photo",
    weight: 47,
    energy: 220,
    protein: 4,
    fat: 10,
    price: 33,
  },
  {
    id: 2,
    title: "mars",
    type: "bar",
    link: "https://upload.wikimedia.org/wikipedia/commons/d/dd/MBar_700.jpg",
    alt: "mars photo",
    weight: 40,
    energy: 200,
    protein: 3,
    fat: 9,
    price: 44,
  },
  {
    id: 3,
    type: "cake",
    title: "mozart",
    link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO14pICLYd4BqSpA4eYMjK_ug6vvDO0Pk-eg&usqp=CAU",
    alt: "mozart photo",
    weight: 1600,
    energy: 2000,
    protein: 3,
    fat: 9,
    price: 450,
  },
  {
    id: 4,
    type: "cake",
    title: "esterhazy",
    link: "https://i0.wp.com/theunicook.com/wp-content/uploads/2021/01/IMG_0302-rotated.jpg?resize=1470%2C680&ssl=1",
    alt: "esterhazy photo",
    weight: 1200,
    energy: 20000,
    protein: 3,
    fat: 9,
    price: 400,
  },
  {
    id: 5,
    type: "icecream",
    title: "Magnum",
    link: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Magnum_ice_cream.jpg/1200px-Magnum_ice_cream.jpg",
    alt: "magnum icecream photo",
    weight: 100,
    energy: 500,
    protein: 3,
    fat: 9,
    price: 20,
  },
  {
    id: 6,
    type: "icecream",
    title: "Soft cream",
    link: "https://media.istockphoto.com/id/163858249/vector/soft-serve-ice-cream-cones.jpg?s=612x612&w=0&k=20&c=uMw5dZD9C3NEan8V-OMQtxY04qdT__lbaLV_3DPb0Jk=",
    alt: "soft cream icecream photo",
    weight: 100,
    energy: 350,
    protein: 3,
    fat: 9,
    price: 5,
  },
  {
    id: 7,
    type: "candy",
    title: "Chupa-Chups",
    link: "https://static.chemistwarehouse.com.au/ams/media/pi/58446/F2D_800.jpg",
    alt: "Chupa-Chups photo",
    weight: 12,
    energy: 150,
    protein: 3,
    fat: 9,
    price: 2,
  },
  {
    id: 8,
    type: "candy",
    title: "Loli-pop",
    link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg_cT29_6uLGv51dthY17PISWA4ZODHqXqYWvApjOFAquIyXoID-o37WwLko0DdqWtCmM&usqp=CA",
    alt: "Loli-pop photo",
    weight: 16,
    energy: 200,
    protein: 3,
    fat: 9,
    price: 1,
  },
  {
    id: 9,
    type: "choco",
    title: "Roshen Caramel Bubble",
    link: "https://irecommend.ru/sites/default/files/imagecache/copyright1/user-images/963435/ORC5dCOeDwA00ggp5pgA.jpg",
    alt: "Roshen Caramel Bubble photo",
    weight: 90,
    energy: 2000,
    protein: 3,
    fat: 9,
    price: 12,
  },
  {
    id: 10,
    type: "choco",
    title: "Roshen Dark Chocolate",
    link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkdxHhwd8Ji17xqgym9eKbJ9803_W6SbBNaA&usqp=CAU",
    alt: "Roshen Dark Chocolate photo",
    weight: 90,
    energy: 2000,
    protein: 3,
    fat: 9,
    price: 10,
  },
  {
    id: 11,
    type: "choco",
    title: "Milka Oreo Chocolate",
    link: "https://c-pi.niceshops.com/upload/image/product/large/default/milka-oreo-chocolate-100-g-917885-en.jpg",
    alt: "Milka Oreo Chocolate photo",
    weight: 90,
    energy: 2000,
    protein: 3,
    fat: 9,
    price: 10,
  },
  {
    id: 12,
    type: "choco",
    title: "Lindt Blo Go Milch",
    link: "https://content2.rozetka.com.ua/goods/images/big/303191543.jpg",
    alt: "Lindt Blo Go Milch photo",
    weight: 300,
    energy: 6000,
    protein: 3,
    fat: 9,
    price: 46,
  },
];
